### ISSUE TITLE
新增 网络请求 的 hostcall

### ISSUE THREAD

**Issue by fahchen** [Byzanteam/jet-programmable-rust-binding#4]
```mermaid
sequenceDiagram
    participant WASM
    participant Elixir
    participant RS as Remote Server

    WASM -->> WASM: allocate memory for the response_ref(ptr, len)
    WASM ->> Elixir: networking request (params, &response_ref)
    Elixir ->> RS: request
    RS ->> Elixir: response
    Elixir -->> Elixir: decode the response into binary
    Elixir -->> WASM: request the specified size (length of binary response) memory 
    WASM -->> Elixir: return the point of the memory
    Elixir -->> Elixir: Write the binary response into the specified memory
    Elixir -->> Elixir: Write (ptr, len) of the bianry response into response_ref
    Elixir ->> WASM: return
    WASM -->> WASM: read (ptr, len) at response_ref
    WASM -->> WASM: read the binary response from memory at (ptr, len)
```

**Comment by danewalters** [comment]
![无标题-2022-11-03-1052](https://user-images.githubusercontent.com/91400014/199878234-33dc07f9-94b3-4ca6-a094-33ac15ed99e0.png)
- 命令行解析使用clap
- http客户端使用reqwest
- 使用colored彩色格式化输出
- 使用anyhow做错误处理
- 使用jsonxf格式化json响应
- mime处理mime类型
- 使用tokio异步处理请求 这个需要后面实现

**Comment by fahchen** [comment]
1. 图试试用 mermaid 画
2. 这里先不给具体的实现（具体的实现会用 Elixir 实现），这里给出来这个能力的定义（比如参数、返回值等是怎么样的等）

**Comment by joeywang321** [comment]
flowchart LR

A[Hard] —> |Text| B (Round)

**Comment by danewalters** [comment]
实现的功能

- git请求参数
- post请求

实现的过程与步骤

传入

- get请求传入URL，String字符串，
- post 请求，需要输入一个 URL，和若干个可选的 key=value，用于提供 json body
- 需要要做两个验证，一是验证 URL，另一个是验证 body。

输出

- 请求返回解析出来的 KvPair 列表，需要装入一个 HashMap，调用HTTP client 的 JSON 方法封装返回。

**Comment by fahchen** [comment]
把函数签名写出来（主要是各种参数返回值的类型）

**Comment by danewalters** [comment]
[rust实现](https://github.com/joeywang321/httpie/blob/main/src/main.rs)，现在在做拆开，put和delete只有语义上面的不同。

**Comment by danewalters** [comment]
# elixir实现方案

需求

- 接受传入的 rust 参数
- 根据传入的参数的请求类型进行不同的网络请求
- 以不同的请求进行参数解析
- 使用finch发起网络请求
- 对返回值进行参数解析，返回定义的数据类型

### 第一步：实现一个基础的模型

实现功能：

- 接受get请求
- 解析get参数
- 发起get请求
- 解析返回参数
- 返回定义参数

### 第二步：添加post，put，delete请求

实现功能

- 接受post，put，delete请求
- 解析post，put，delete参数
- 发起对应的请求
- 解析返回的参数
- 返回定义的参数

### 第三步：实现异步网络请求

实现功能

- 网络请求的异步处理

### 第四步：实现错误，异常处理

实现功能

- 参数错误，异常
- 请求超时
- 请求连接池实现自定义
